### ISSUE TITLE
fix gulpfile Error

### ISSUE THREAD

**Issue by kenmori** [kenmori/angular_typescript#14]
```
Error: Forbidden
    at createError (/Users/No51/Desktop/Git/angular_typescript/1507-08/node_modules/gulp-connect/node_modules/connect/node_modules/serve-index/index.js:188:13)
    at Object.directory [as handle] (/Users/No51/Desktop/Git/angular_typescript/1507-08/node_modules/gulp-connect/node_modules/connect/node_modules/serve-index/index.js:100:46)
    at next (/Users/No51/Desktop/Git/angular_typescript/1507-08/node_modules/gulp-connect/node_modules/connect/lib/proto.js:194:15)
    at SendStream.error (/Users/No51/Desktop/Git/angular_typescript/1507-08/node_modules/gulp-connect/node_modules/connect/node_modules/serve-static/index.js:86:37)
    at SendStream.emit (events.js:95:17)
    at SendStream.error (/Users/No51/Desktop/Git/angular_typescript/1507-08/node_modules/gulp-connect/node_modules/connect/node_modules/serve-static/node_modules/send/lib/send.js:172:51)
    at SendStream.onStatError (/Users/No51/Desktop/Git/angular_typescript/1507-08/node_modules/gulp-connect/node_modules/connect/node_modules/serve-static/node_modules/send/lib/send.js:285:48)
    at /Users/No51/Desktop/Git/angular_typescript/1507-08/node_modules/gulp-connect/node_modules/connect/node_modules/serve-static/node_modules/send/lib/send.js:378:26
    at Object.oncomplete (fs.js:107:15)


```

**Comment by kenmori** [comment]
https://github.com/AveVlad/gulp-connect/issues/38

remove 

```
root: '.',  
```
